version: '3.7'

services:
  backend:
    build: ./simple-api-student
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./db
    networks:
      - my-network

  httpd:
    build: ./http
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
