- name: Clean packages
  command:
    cmd: yum clean all -y

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add repo docker
  command:
    cmd: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Install python3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Pip install
  pip:
    name: docker
    executable: pip3

- name: Make sure Docker is running
  service:
    name: docker
    state: started
  tags: docker


