name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and test with Maven
        run: mvn -B verify
        working-directory: backend

  build-and-push-docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build and publish Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: true
          tags: djedjiga18/tp1-backend:latest

