name: CI devops 2023

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          context : ./simple-api-student/
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api-student/

  build-and-push-docker-image:
    needs : test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
         context: ./simple-api-student/
         tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/api
         push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./db/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/db
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http/
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/http
          push: ${{ github.ref == 'refs/heads/main' }}