name: CI devops 2023

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          context : ./simple-api-student/
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api-student/

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: simple-api-student
          dockerfile: Dockerfile
          push: true
          #tags: your-docker-hub-username/backend:latest

      - name: Build and push database Docker image
        uses: docker/build-push-action@v2
        with:
          context: db
          dockerfile: Dockerfile
          push: true
          #tags: your-docker-hub-username/database:latest

      - name: Build and push httpd Docker image
        uses: docker/build-push-action@v2
        with:
          context: http
          dockerfile: Dockerfile
          push: true
          #tags: your-docker-hub-username/httpd:latest


